title: blog
author:
  name: Guillaume Fetter
  email: guillaume.fetter@northvolt.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Blog posts about Software and Data Engineering

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/).
# If you want to use the latest Minima version on GitHub Pages, use the following setting and
# add a line comment on "theme: minima" above.
remote_theme: jekyll/minima

plugins:
  - jekyll-feed

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: classic
  date_format: "%Y-%m-%d"
  # Generate social links in footer.
  social_links:
    - { platform: github, user_url: "https://github.com/guillaume-fetter" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/guillaume-facchini-fetter-50a2a889/",
      }
